package RegelTaal.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.INamedConcept_BehaviorDescriptor;

/**
 * Will be removed after 3.3
 * Need to support compilation of the legacy behavior descriptors before the language is rebuilt
 * This class is not involved in the actual method invocation
 */
@Deprecated
public class Actie_BehaviorDescriptor extends AbstracteActie_BehaviorDescriptor implements INamedConcept_BehaviorDescriptor {

  @Override
  public String getConceptFqName() {
    return "RegelTaal.structure.Actie";
  }

}
