package RegelTaal.behavior;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.openapi.editor.EditorComponent;
import jetbrains.mps.openapi.editor.update.UpdaterListener;

/**
 * Will be removed after 3.3
 * Need to support the legacy static direct method calls
 */
@Deprecated
public class Voorwaarde_Behavior {
  public static void call_refreshname_6655185614570722471(SNode __thisNode__) {
    Voorwaarde__BehaviorDescriptor.refreshname_id5LrY0T6LLiB(__thisNode__);
  }
  public static void call_SetEditorContext_6655185614570814871(SNode __thisNode__, EditorComponent editorComponent) {
    Voorwaarde__BehaviorDescriptor.SetEditorContext_id5LrY0T6M7Qn(__thisNode__, editorComponent);
  }
  public static UpdaterListener call_createListener_8794515008209972274(SNode __thisNode__, final EditorComponent editorComponent) {
    return Voorwaarde__BehaviorDescriptor.createListener_id7CcpcRWcAKM(__thisNode__, editorComponent);
  }
}
