package RegelTaal.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {

  /*package*/ final ConceptDescriptor myConceptAbstracteActie = new ConceptDescriptorBuilder("RegelTaal.structure.AbstracteActie", MetaIdFactory.conceptId(0x6d5fd5261cea4e31L, 0xab59ad955823700cL, 0x7b09cf0db9d86bbcL)).super_("jetbrains.mps.lang.core.structure.BaseConcept").super_(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL)).parents("jetbrains.mps.lang.core.structure.BaseConcept", "jetbrains.mps.lang.core.structure.INamedConcept").parentIds(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL), MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L)).abstract_().create();
  /*package*/ final ConceptDescriptor myConceptAbstracteModaliteit = new ConceptDescriptorBuilder("RegelTaal.structure.AbstracteModaliteit", MetaIdFactory.conceptId(0x6d5fd5261cea4e31L, 0xab59ad955823700cL, 0x1878635738437c40L)).super_("jetbrains.mps.lang.core.structure.BaseConcept").super_(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL)).parents("jetbrains.mps.lang.core.structure.BaseConcept").parentIds(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL)).abstract_().create();
  /*package*/ final ConceptDescriptor myConceptAbstracteOperand = new ConceptDescriptorBuilder("RegelTaal.structure.AbstracteOperand", MetaIdFactory.conceptId(0x6d5fd5261cea4e31L, 0xab59ad955823700cL, 0x5c5bf80e46c2b0b8L)).super_("jetbrains.mps.lang.core.structure.BaseConcept").super_(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL)).parents("jetbrains.mps.lang.core.structure.BaseConcept").parentIds(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL)).abstract_().create();
  /*package*/ final ConceptDescriptor myConceptAbstracteOperator = new ConceptDescriptorBuilder("RegelTaal.structure.AbstracteOperator", MetaIdFactory.conceptId(0x6d5fd5261cea4e31L, 0xab59ad955823700cL, 0x18786357384414e6L)).super_("jetbrains.mps.lang.core.structure.BaseConcept").super_(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL)).parents("jetbrains.mps.lang.core.structure.BaseConcept").parentIds(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL)).abstract_().create();
  /*package*/ final ConceptDescriptor myConceptAbstracteVoorwaarde = new ConceptDescriptorBuilder("RegelTaal.structure.AbstracteVoorwaarde", MetaIdFactory.conceptId(0x6d5fd5261cea4e31L, 0xab59ad955823700cL, 0x7b09cf0db9d86bc4L)).super_("jetbrains.mps.lang.core.structure.BaseConcept").super_(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL)).parents("jetbrains.mps.lang.core.structure.BaseConcept").parentIds(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL)).abstract_().create();
  /*package*/ final ConceptDescriptor myConceptActie = new ConceptDescriptorBuilder("RegelTaal.structure.Actie", MetaIdFactory.conceptId(0x6d5fd5261cea4e31L, 0xab59ad955823700cL, 0x7b09cf0db9d86bc1L)).super_("RegelTaal.structure.AbstracteActie").super_(MetaIdFactory.conceptId(0x6d5fd5261cea4e31L, 0xab59ad955823700cL, 0x7b09cf0db9d86bbcL)).parents("RegelTaal.structure.AbstracteActie", "jetbrains.mps.lang.core.structure.INamedConcept").parentIds(MetaIdFactory.conceptId(0x6d5fd5261cea4e31L, 0xab59ad955823700cL, 0x7b09cf0db9d86bbcL), MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L)).propertyDescriptors(new ConceptDescriptorBuilder.Prop(1763268480372729153L, "text")).properties("text").create();
  /*package*/ final ConceptDescriptor myConceptActieReferentie = new ConceptDescriptorBuilder("RegelTaal.structure.ActieReferentie", MetaIdFactory.conceptId(0x6d5fd5261cea4e31L, 0xab59ad955823700cL, 0x7b09cf0db9d86bc0L)).super_("RegelTaal.structure.AbstracteActie").super_(MetaIdFactory.conceptId(0x6d5fd5261cea4e31L, 0xab59ad955823700cL, 0x7b09cf0db9d86bbcL)).parents("RegelTaal.structure.AbstracteActie").parentIds(MetaIdFactory.conceptId(0x6d5fd5261cea4e31L, 0xab59ad955823700cL, 0x7b09cf0db9d86bbcL)).referenceDescriptors(new ConceptDescriptorBuilder.Ref(6529903266855536561L, "actie", MetaIdFactory.conceptId(0x6d5fd5261cea4e31L, 0xab59ad955823700cL, 0x7b09cf0db9d86bc1L), false)).references("actie").create();
  /*package*/ final ConceptDescriptor myConceptIsNietWaar = new ConceptDescriptorBuilder("RegelTaal.structure.IsNietWaar", MetaIdFactory.conceptId(0x6d5fd5261cea4e31L, 0xab59ad955823700cL, 0x187863573844151aL)).super_("RegelTaal.structure.AbstracteOperator").super_(MetaIdFactory.conceptId(0x6d5fd5261cea4e31L, 0xab59ad955823700cL, 0x18786357384414e6L)).parents("RegelTaal.structure.AbstracteOperator").parentIds(MetaIdFactory.conceptId(0x6d5fd5261cea4e31L, 0xab59ad955823700cL, 0x18786357384414e6L)).create();
  /*package*/ final ConceptDescriptor myConceptIsWaar = new ConceptDescriptorBuilder("RegelTaal.structure.IsWaar", MetaIdFactory.conceptId(0x6d5fd5261cea4e31L, 0xab59ad955823700cL, 0x18786357384414e7L)).super_("RegelTaal.structure.AbstracteOperator").super_(MetaIdFactory.conceptId(0x6d5fd5261cea4e31L, 0xab59ad955823700cL, 0x18786357384414e6L)).parents("RegelTaal.structure.AbstracteOperator").parentIds(MetaIdFactory.conceptId(0x6d5fd5261cea4e31L, 0xab59ad955823700cL, 0x18786357384414e6L)).create();
  /*package*/ final ConceptDescriptor myConceptMagNiet = new ConceptDescriptorBuilder("RegelTaal.structure.MagNiet", MetaIdFactory.conceptId(0x6d5fd5261cea4e31L, 0xab59ad955823700cL, 0x1878635738437c7eL)).super_("RegelTaal.structure.AbstracteModaliteit").super_(MetaIdFactory.conceptId(0x6d5fd5261cea4e31L, 0xab59ad955823700cL, 0x1878635738437c40L)).parents("RegelTaal.structure.AbstracteModaliteit").parentIds(MetaIdFactory.conceptId(0x6d5fd5261cea4e31L, 0xab59ad955823700cL, 0x1878635738437c40L)).create();
  /*package*/ final ConceptDescriptor myConceptMoet = new ConceptDescriptorBuilder("RegelTaal.structure.Moet", MetaIdFactory.conceptId(0x6d5fd5261cea4e31L, 0xab59ad955823700cL, 0x1878635738437c43L)).super_("RegelTaal.structure.AbstracteModaliteit").super_(MetaIdFactory.conceptId(0x6d5fd5261cea4e31L, 0xab59ad955823700cL, 0x1878635738437c40L)).parents("RegelTaal.structure.AbstracteModaliteit").parentIds(MetaIdFactory.conceptId(0x6d5fd5261cea4e31L, 0xab59ad955823700cL, 0x1878635738437c40L)).create();
  /*package*/ final ConceptDescriptor myConceptOperand = new ConceptDescriptorBuilder("RegelTaal.structure.Operand", MetaIdFactory.conceptId(0x6d5fd5261cea4e31L, 0xab59ad955823700cL, 0x5c5bf80e46c2b0b9L)).super_("RegelTaal.structure.AbstracteOperand").super_(MetaIdFactory.conceptId(0x6d5fd5261cea4e31L, 0xab59ad955823700cL, 0x5c5bf80e46c2b0b8L)).parents("RegelTaal.structure.AbstracteOperand", "jetbrains.mps.lang.core.structure.INamedConcept").parentIds(MetaIdFactory.conceptId(0x6d5fd5261cea4e31L, 0xab59ad955823700cL, 0x5c5bf80e46c2b0b8L), MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L)).create();
  /*package*/ final ConceptDescriptor myConceptOperandReferentie = new ConceptDescriptorBuilder("RegelTaal.structure.OperandReferentie", MetaIdFactory.conceptId(0x6d5fd5261cea4e31L, 0xab59ad955823700cL, 0x5c5bf80e46c3b9e7L)).super_("RegelTaal.structure.AbstracteOperand").super_(MetaIdFactory.conceptId(0x6d5fd5261cea4e31L, 0xab59ad955823700cL, 0x5c5bf80e46c2b0b8L)).parents("RegelTaal.structure.AbstracteOperand").parentIds(MetaIdFactory.conceptId(0x6d5fd5261cea4e31L, 0xab59ad955823700cL, 0x5c5bf80e46c2b0b8L)).referenceDescriptors(new ConceptDescriptorBuilder.Ref(6655185614570502632L, "operand", MetaIdFactory.conceptId(0x6d5fd5261cea4e31L, 0xab59ad955823700cL, 0x5c5bf80e46c2b0b9L), false)).references("operand").create();
  /*package*/ final ConceptDescriptor myConceptRegel = new ConceptDescriptorBuilder("RegelTaal.structure.Regel", MetaIdFactory.conceptId(0x6d5fd5261cea4e31L, 0xab59ad955823700cL, 0x7b09cf0db9d86bbaL)).super_("jetbrains.mps.lang.core.structure.BaseConcept").super_(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL)).parents("jetbrains.mps.lang.core.structure.BaseConcept", "jetbrains.mps.lang.core.structure.INamedConcept").parentIds(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL), MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L)).childDescriptors(new ConceptDescriptorBuilder.Link(8865844999315024839L, "actie", MetaIdFactory.conceptId(0x6d5fd5261cea4e31L, 0xab59ad955823700cL, 0x7b09cf0db9d86bbcL), false, false, false), new ConceptDescriptorBuilder.Link(1763268480372800682L, "modaliteit", MetaIdFactory.conceptId(0x6d5fd5261cea4e31L, 0xab59ad955823700cL, 0x1878635738437c40L), false, false, false), new ConceptDescriptorBuilder.Link(8865844999315024841L, "voorwaarden", MetaIdFactory.conceptId(0x6d5fd5261cea4e31L, 0xab59ad955823700cL, 0x7b09cf0db9d86bc4L), true, true, false)).children(new String[]{"actie", "modaliteit", "voorwaarden"}, new boolean[]{false, false, true}).create();
  /*package*/ final ConceptDescriptor myConceptRegelgroep = new ConceptDescriptorBuilder("RegelTaal.structure.Regelgroep", MetaIdFactory.conceptId(0x6d5fd5261cea4e31L, 0xab59ad955823700cL, 0x5a9ee06c9e98068bL)).super_("jetbrains.mps.lang.core.structure.BaseConcept").super_(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL)).parents("jetbrains.mps.lang.core.structure.BaseConcept", "jetbrains.mps.lang.core.structure.INamedConcept").parentIds(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL), MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L)).childDescriptors(new ConceptDescriptorBuilder.Link(6529903266855650956L, "regels", MetaIdFactory.conceptId(0x6d5fd5261cea4e31L, 0xab59ad955823700cL, 0x7b09cf0db9d86bbaL), true, true, false)).children(new String[]{"regels"}, new boolean[]{true}).create();
  /*package*/ final ConceptDescriptor myConceptVoorwaarde = new ConceptDescriptorBuilder("RegelTaal.structure.Voorwaarde", MetaIdFactory.conceptId(0x6d5fd5261cea4e31L, 0xab59ad955823700cL, 0x7b09cf0db9d86bbbL)).super_("RegelTaal.structure.AbstracteVoorwaarde").super_(MetaIdFactory.conceptId(0x6d5fd5261cea4e31L, 0xab59ad955823700cL, 0x7b09cf0db9d86bc4L)).parents("RegelTaal.structure.AbstracteVoorwaarde", "jetbrains.mps.lang.core.structure.INamedConcept").parentIds(MetaIdFactory.conceptId(0x6d5fd5261cea4e31L, 0xab59ad955823700cL, 0x7b09cf0db9d86bc4L), MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L)).childDescriptors(new ConceptDescriptorBuilder.Link(6655185614570502617L, "operand", MetaIdFactory.conceptId(0x6d5fd5261cea4e31L, 0xab59ad955823700cL, 0x5c5bf80e46c2b0b8L), false, false, false), new ConceptDescriptorBuilder.Link(1763268480372839754L, "operator", MetaIdFactory.conceptId(0x6d5fd5261cea4e31L, 0xab59ad955823700cL, 0x18786357384414e6L), false, false, false)).children(new String[]{"operand", "operator"}, new boolean[]{false, false}).create();
  /*package*/ final ConceptDescriptor myConceptVoorwaardeReferentie = new ConceptDescriptorBuilder("RegelTaal.structure.VoorwaardeReferentie", MetaIdFactory.conceptId(0x6d5fd5261cea4e31L, 0xab59ad955823700cL, 0x7b09cf0db9d86bbdL)).super_("RegelTaal.structure.AbstracteVoorwaarde").super_(MetaIdFactory.conceptId(0x6d5fd5261cea4e31L, 0xab59ad955823700cL, 0x7b09cf0db9d86bc4L)).parents("RegelTaal.structure.AbstracteVoorwaarde").parentIds(MetaIdFactory.conceptId(0x6d5fd5261cea4e31L, 0xab59ad955823700cL, 0x7b09cf0db9d86bc4L)).referenceDescriptors(new ConceptDescriptorBuilder.Ref(8865844999315024830L, "voorwaarde", MetaIdFactory.conceptId(0x6d5fd5261cea4e31L, 0xab59ad955823700cL, 0x7b09cf0db9d86bbbL), false)).references("voorwaarde").create();

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptAbstracteActie, myConceptAbstracteModaliteit, myConceptAbstracteOperand, myConceptAbstracteOperator, myConceptAbstracteVoorwaarde, myConceptActie, myConceptActieReferentie, myConceptIsNietWaar, myConceptIsWaar, myConceptMagNiet, myConceptMoet, myConceptOperand, myConceptOperandReferentie, myConceptRegel, myConceptRegelgroep, myConceptVoorwaarde, myConceptVoorwaardeReferentie);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(String conceptFqName) {
    switch (Arrays.binarySearch(stringSwitchCases_1htk8d_a0a0v, conceptFqName)) {
      case 0:
        return myConceptAbstracteActie;
      case 1:
        return myConceptAbstracteModaliteit;
      case 2:
        return myConceptAbstracteOperand;
      case 3:
        return myConceptAbstracteOperator;
      case 4:
        return myConceptAbstracteVoorwaarde;
      case 5:
        return myConceptActie;
      case 6:
        return myConceptActieReferentie;
      case 7:
        return myConceptIsNietWaar;
      case 8:
        return myConceptIsWaar;
      case 9:
        return myConceptMagNiet;
      case 10:
        return myConceptMoet;
      case 11:
        return myConceptOperand;
      case 12:
        return myConceptOperandReferentie;
      case 13:
        return myConceptRegel;
      case 14:
        return myConceptRegelgroep;
      case 15:
        return myConceptVoorwaarde;
      case 16:
        return myConceptVoorwaardeReferentie;
      default:
        return null;
    }
  }
  private static String[] stringSwitchCases_1htk8d_a0a0v = new String[]{"RegelTaal.structure.AbstracteActie", "RegelTaal.structure.AbstracteModaliteit", "RegelTaal.structure.AbstracteOperand", "RegelTaal.structure.AbstracteOperator", "RegelTaal.structure.AbstracteVoorwaarde", "RegelTaal.structure.Actie", "RegelTaal.structure.ActieReferentie", "RegelTaal.structure.IsNietWaar", "RegelTaal.structure.IsWaar", "RegelTaal.structure.MagNiet", "RegelTaal.structure.Moet", "RegelTaal.structure.Operand", "RegelTaal.structure.OperandReferentie", "RegelTaal.structure.Regel", "RegelTaal.structure.Regelgroep", "RegelTaal.structure.Voorwaarde", "RegelTaal.structure.VoorwaardeReferentie"};
}
