package ContextTaal.structure;

/*Generated by MPS */

import java.util.List;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import java.util.LinkedList;

public enum RegelPresentatie {
  Regels("Regels", "Regels"),
  Tabel("Beslistabel", "Tabel");

  private final String myName;
  public String getName() {
    return myName;
  }
  private final String myValue;
  private RegelPresentatie(String name, String value) {
    myName = name;
    myValue = value;
  }
  public String getValue() {
    return myValue;
  }
  public String getValueAsString() {
    return myValue;
  }
  public static List<RegelPresentatie> getConstants() {
    List<RegelPresentatie> list = ListSequence.fromList(new LinkedList<RegelPresentatie>());
    ListSequence.fromList(list).addElement(RegelPresentatie.Regels);
    ListSequence.fromList(list).addElement(RegelPresentatie.Tabel);
    return list;
  }
  public static RegelPresentatie getDefault() {
    return RegelPresentatie.Regels;
  }
  public static RegelPresentatie parseValue(String value) {
    if (value == null) {
      return RegelPresentatie.getDefault();
    }
    if (value.equals(RegelPresentatie.Regels.getValueAsString())) {
      return RegelPresentatie.Regels;
    }
    if (value.equals(RegelPresentatie.Tabel.getValueAsString())) {
      return RegelPresentatie.Tabel;
    }
    return RegelPresentatie.getDefault();
  }
}
